# Generated by Django 3.2.7 on 2021-09-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentee',
            name='volun_endDate',
        ),
        migrations.RemoveField(
            model_name='mentee',
            name='volun_startDate',
        ),
    ]
