# Generated by Django 3.2.6 on 2021-08-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='volunType',
            field=models.CharField(choices=[('Online', '온라인'), ('Offline', '오프라인')], max_length=10, null=True),
        ),
    ]
