# Generated by Django 3.2.6 on 2021-08-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210819_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='center_latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mentor',
            name='center_longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
