# Generated by Django 3.2.6 on 2021-08-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterModelOptions(
            name='mentor',
            options={'ordering': ('-pub_date',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterField(
            model_name='mentor',
            name='title',
            field=models.CharField(max_length=100, verbose_name='TITLE'),
        ),
        migrations.AlterModelTable(
            name='mentor',
            table='blog_posts',
        ),
    ]
