# Generated by Django 3.2.7 on 2021-09-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210909_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='volunType',
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentoringType',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='mentoringType',
            field=models.TextField(blank=True),
        ),
    ]
