# Generated by Django 3.2.6 on 2021-08-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210824_0432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Mentors', 'verbose_name_plural': 'Mentors'},
        ),
        migrations.AlterModelTable(
            name='mentor',
            table='blog_Mentors_post',
        ),
    ]
