# Generated by Django 3.2.7 on 2021-09-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210909_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='subject',
            field=models.TextField(blank=True),
        ),
    ]
