# Generated by Django 3.2.6 on 2021-08-23 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210824_0433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Mentors', 'verbose_name_plural': 'Mentor'},
        ),
    ]
