# Generated by Django 3.2.6 on 2021-08-23 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_mentor_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mentor',
            table='blog_Mentors_board',
        ),
    ]
