# Generated by Django 3.2.6 on 2021-08-24 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_mentor_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성 날짜'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='title',
            field=models.CharField(max_length=100, verbose_name='제목'),
        ),
    ]
