# Generated by Django 3.2.6 on 2021-08-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210824_0900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={},
        ),
        migrations.AlterModelTable(
            name='mentor',
            table=None,
        ),
    ]
