# Generated by Django 3.2.6 on 2021-08-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210826_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='title',
            field=models.CharField(max_length=100, verbose_name='제목'),
        ),
    ]
